### ISSUE TITLE
Suggestion for Relevant Work on Your Repository

### ISSUE THREAD

**Issue by RuyuanWan** [mainlp/awesome-human-label-variation#5]
Hello,

I'm reaching out to express my appreciation for the valuable open-source repository you've organized!

In line with your project's theme, I'd like to suggest adding my recent AAAI paper, "[Everyone's Voice Matters: Quantifying Annotation Disagreement Using Demographic Information](https://arxiv.org/abs/2301.05036)" to the key references of your GitHub repository.

This paper takes a unique look at label variation by studying the impact of annotators' demographics on their disagreements in NLP tasks. Our findings reveal that demographic information, such as gender, ethnicity, and education level, is instrumental in predicting annotator disagreements.

I look forward to hearing from you.

Best regards,
Ruyuan

**Comment by bplank** [comment]
hi @RuyuanWan
Many thanks for this reference and the list of datasets.
